name: CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

  workflow_dispatch:

jobs:
  test:
    name: Build and Test
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Show Swift and Xcode versions
        run: |
          swift --version
          xcodebuild -version

      - name: Build and Test
        run: |
          xcodebuild \
            -scheme TrisNotificationKit \
            -destination 'platform=iOS Simulator,name=iPhone 16' \
            -configuration Debug \
            CODE_SIGNING_ALLOWED=NO \
            test
